// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyConfig(arg1:main.NetworkConfig):Promise<string>;

export function DeleteProfile(arg1:string):Promise<Array<main.SavedProfile>>;

export function GetAdapterConfig(arg1:string):Promise<main.NetworkConfig>;

export function GetAppState():Promise<main.AppState>;

export function ListAdapters():Promise<Array<main.NetworkAdapter>>;

export function LoadProfiles():Promise<Array<main.SavedProfile>>;

export function SaveProfile(arg1:string,arg2:main.NetworkConfig):Promise<Array<main.SavedProfile>>;
