// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyConfig(arg1) {
  return window['go']['main']['App']['ApplyConfig'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function GetAdapterConfig(arg1) {
  return window['go']['main']['App']['GetAdapterConfig'](arg1);
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function ListAdapters() {
  return window['go']['main']['App']['ListAdapters']();
}

export function LoadProfiles() {
  return window['go']['main']['App']['LoadProfiles']();
}

export function SaveProfile(arg1, arg2) {
  return window['go']['main']['App']['SaveProfile'](arg1, arg2);
}
